[build.default]
foundry-project-root       = '.'
regen                      = true
rekompile                  = true
verbose                    = false
debug                      = false
require                    = 'test/solady-lemmas.k'
module-import              = 'FixedPointMathLibVerification:SOLADY-LEMMAS'

[prove.default]
symbolic-immutables        = false
assume-defined             = false
no-log-rewrites            = false
foundry-project-root       = '.'
verbose                    = false
debug                      = false
max-depth                  = 100000
max-iterations             = 10000
reinit                     = false
cse                        = false
workers                    = 1
failure-information        = false
counterexample-information = false
minimize-proofs            = false
fail-fast                  = true
smt-timeout                = 5000
smt-retry-limit            = 0
break-every-step           = false
break-on-jumpi             = false
break-on-calls             = false
break-on-storage           = false
break-on-basic-blocks      = false
break-on-cheatcodes        = false
run-constructor            = false
kore-rpc-command           = 'kore-rpc-booster --no-post-exec-simplify'
match-test                 = [ 'FixedPointMathLibVerification.testLog2']
optimize-performance       = 6

[show.default]
foundry-project-root       = '.'
verbose                    = false
debug                      = false
