name: 'Master Push'
on:
  push:
    branches:
      - 'master'

jobs:

  cut-release:
    name: 'Cut Release'
    runs-on: [self-hosted, linux, flyweight]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.push.head.sha }}
          fetch-depth: 0

      - name: 'Create release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          short_sha=$(git rev-parse --short ${{ github.sha }})
          gh release create ${short_sha} --target ${{ github.sha }}
