---
name: 'Test PR'
on:
  pull_request:
    branches:
      - "master"

# Stop in progress workflows on the same branch and same workflow to use latest committed code
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  new-version-test:
    name: 'Test Proofs'
    runs-on: [self-hosted, linux, normal]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.JENKINS_GITHUB_PAT }}
          fetch-depth: 0
      
      - name: 'Get Kontrol Version'
        run: |
          set -euo pipefail
          # Get the version of the tool from the Dockerfile
          echo "kontrol-version=$(cat deps/kontrol_release)" >> $GITHUB_ENV
          # Get Repository Base name
          echo "repository_basename=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Docker Login w/ Github Token
        uses: docker/login-action@v1
        with:
          username: rvdockerhub
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Start Docker Container"
        uses: ./.github/actions/with-docker
        with:
          container-name: '${{ env.repository_basename }}-ci'

      - name: 'Test New Tool Versions'
        run: |
          # Run the following in the running docker container
          docker exec -u user ${{ env.repository_basename }}-ci bash -c './test/run-kevm.sh'

      - name: 'Stop Docker Container'
        if: always()
        run: |
          docker stop --time=0 ${{ env.repository_basename }}-ci
